### ISSUE TITLE
Easy dowload

### ISSUE THREAD

**Issue by 6ix-Raptors** [andreivdev/coolm1#3]
Can you please make a way to download your app easily? Im very new to coding and also GitHub so im unsure how do download your app. Thanks.

**Comment by andreivdev** [comment]
Looks like a code sign issue.

It will take a couple of days before I can fix it.

Until then you can clone the repo and build it yourself using npm install and npm run make.

**Comment by andreivdev** [comment]
Can you try [v0.1.2](https://github.com/andreivdev/coolm1/releases/tag/v0.1.2) ?

I signed the application and you should be able to run it now, but because I don't have an Apple Developer account yet and I can't notarize it, you will receive a warning when you first open it.

You can bypass that warning by allowing it in Settings -> Security

<img width="666" alt="Screenshot 2021-05-31 at 09 18 08" src="https://user-images.githubusercontent.com/8058187/120149283-2875fe80-c1f2-11eb-9c5f-36c16e9027f4.png">

I enrolled in the Apple Developer program, but it takes a while before they confirm my account. Once that's done, I will release a signed and notarized version which does not show the security warning anymore.

**Comment by andreivdev** [comment]
https://github.com/andreivdev/coolm1/releases/tag/v1.0.0

Here is a notarized version :)

**Comment by 6ix-Raptors** [comment]
Thank you so much! This is so helpful, I appreciate your work.
