### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by 6ix-Raptors** [andreivdev/coolm1#4]
Hello, 

I really enjoy using the application! Its amazing its for free as many other temperature checkers such as TG Pro are paid and there are not too many alternatives for M1. I was wondering if you would be able to make the temperature show in the menu bar as it would be a little more continent. There is an app called EUL on GitHub that monitors temp, ram, storage as well as other things and I use it all the time. The issue with that application is the creator of it does not own an M1 mac and is therefore unable to add the temperature checking code for m1 specifically. If your able to get some ideas from EUL and implement it in coolm1 or even work on an M1 version of EUL that would be amazing. A lot of people I know IRL and on social media such as Reddit would love to see an M1 version as well. Thanks for your time, and I will be continuing to use your amazing application.

**Comment by andreivdev** [comment]
Hey

Thanks for the kind words

I’ll see what I can do :D

**Comment by andreivdev** [comment]
Done.

Feature added in [v.1.1.0](https://github.com/andreivdev/coolm1/releases/tag/v1.1.0)

As a side effect, the app has to open itself for a second at startup in order to load the sensors and be able to show the temperature in the tray. That's a limitation of electron, I can't get around it.

<img width="708" alt="Screenshot 2021-06-05 at 13 07 38" src="https://user-images.githubusercontent.com/8058187/120888099-37e4b580-c5ff-11eb-8843-b081fcf7b078.png">
